name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      # Publish nuget package
      - name: Pack
        run: dotnet pack MhLabs.AwsCliSso/MhLabs.AwsCliSso.csproj -c Release
                
      - name: Publish to Nuget
        run: dotnet nuget push /home/runner/work/MhLabs.AwsCliSso/MhLabs.AwsCliSso/MhLabs.AwsCliSso/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate